### ISSUE TITLE
JavaScript Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#16]
This issue was originally raised via forum topic: [https://forum.groupdocs.com/t/github-asp-net-mvc-demo-is-not-working/6912](https://forum.groupdocs.com/t/github-asp-net-mvc-demo-is-not-working/6912)

The JavaScript error _"Cannot read property 'length' of undefined"_ occurs when loading any document in the viewer. The error occurs at _Line: 723_ of _viewer.js_.
Error details: 
![jserror](https://user-images.githubusercontent.com/16013722/51012567-8fda7780-157f-11e9-9296-c1ced5b41103.png)

**Comment by Pavel-Teplitsky** [comment]
Hi @usmanazizgroupdocs,  please try updated version

**Comment by usmanazizgroupdocs** [comment]
@Pavel-Teplitsky ,
The issue is resolved in the updated version.
Regards
