### ISSUE TITLE
Problems with MVC project

### ISSUE THREAD

**Issue by gboscolo** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#2]
Hi! i've faced some problem with the mvc test project:

- in firefox the thumbnails are displayed as big as the document preview;
- in IE the project doesn't work (ES6 fat arrow notation)
- clicking on the last thumbnail make a js error

**Comment by bobkovalex** [comment]
Hi,

We will check reported issues, however please note that we do **not** support IE.

**Comment by Pavel-Teplitsky** [comment]
Hi,

Following issues has been fixed in 6c19fab commit:
* in firefox the thumbnails are displayed as big as the document preview;
* clicking on the last thumbnail make a js error;
