### ISSUE TITLE
Unable to run the latest release

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#36]
While running the latest release of the application, I am getting the following errors in the browser's console, however, the project builds successfully in VS2015. 
![Errors](https://user-images.githubusercontent.com/16013722/58657796-7bcdc180-8338-11e9-8751-cf0fb2d94d3a.png)

**Comment by Pavel-Teplitsky** [comment]
Hi @usmanazizgroupdocs , thank you for your request. From the error, from your screenshot I can see that you tried to open examples web page via wrong URL htt://localhost:8080/viewer/Viewer/Index, please try to open htt://localhost:8080/viewer instead.

Best regards.

**Comment by usmanazizgroupdocs** [comment]
@Pavel-Teplitsky Thanks for the solution. It worked.
