### ISSUE TITLE
The print preview of the JPEG is zoomed in

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#39]
This issue is raised via the forum topic: [https://forum.groupdocs.com/t/problem-printing-jpeg-file/7320/6](https://forum.groupdocs.com/t/problem-printing-jpeg-file/7320/6)

When printing the rendered JPEG files using the _Print_ button, the content is zoomed in and only a portion of the page appears in the print preview (see [screenshot](https://i.imgur.com/SvaLcsi.png)).
The sample JPEG file is attached. The issue appears in both the HTML based and Image-based rendering. Would you please investigate?
![test](https://user-images.githubusercontent.com/16013722/59048867-32352780-88a0-11e9-9b04-1aa1b8c3830c.jpg)

**Comment by Pavel-Teplitsky** [comment]
Hi @usmanazizgroupdocs I will check this issue and return to you.

Best regards.

**Comment by Pavel-Teplitsky** [comment]
Hi @usmanazizgroupdocs We have fixed the issue. Please clean and rebuild you solution to load updated front-end resources.

Best regadrs.

**Comment by usmanazizgroupdocs** [comment]
@Pavel-Teplitsky  Thanks.
