### ISSUE TITLE
Module not found : error : Can’t resolve ‘ng-click-outside’

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#43]
This issue was raised via the forum topic: [https://forum.groupdocs.com/t/groupdocs-viewer-for-net-mvc-sample-code/7508](https://forum.groupdocs.com/t/groupdocs-viewer-for-net-mvc-sample-code/7508)

> **When I try try to run the sample code I get a build error**
> 
> ERROR in C:/Src/GroupDocs/src/client/node_modules/@groupdocs.examples.angular/common-components/fesm5/groupdocs.examples.angular-common-components.js
> 1>Module not found : error : Can’t resolve ‘ng-click-outside’ in ‘C:\Src\GroupDocs\src\client\node_modules@groupdocs.examples.angular\common-components\fesm5’
> 1> npm ERR! code ELIFECYCLE
> 1> npm ERR! errno 1
> 1> npm ERR! client@0.0.0 build: ..\..\packages\Node-Kit.11.1.0.1\node\win\node.exe .\node_modules\@angular\cli\bin\ng build
> 1> npm ERR! Exit status 1
> 1> npm ERR!
> 1> npm ERR! Failed at the client@0.0.0 build script.
> 1> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 1>
> 
> **I am using Visual Studio 2019.**

**Comment by egorovpavel** [comment]
Hi @usmanazizgroupdocs. We identified and fixed issue you mentioned. This issue was related with missed dependency in published package. Once you rebuild your fronted solution new fixed package will be installed.
