### ISSUE TITLE
Master branch have missing code

### ISSUE THREAD

**Issue by ronald6112** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#45]
Hi,
I have downloaded cod from Master branch but it has some missing code in 'Resource' folder.
After restoring all nuget package, Project run successfully but have some console error as per attached snap shot.

![Capture](https://user-images.githubusercontent.com/54881372/64231191-8c2fa280-cf0c-11e9-8719-c878ed978935.PNG)
Thanks.

**Comment by kegor** [comment]
Hi @ronald6112, the fix will be shipped in the next release of https://github.com/groupdocs-total/GroupDocs.Total-Angular during this week.

**Comment by kegor** [comment]
Closing, because related PR (https://github.com/groupdocs-total/GroupDocs.Total-Angular/pull/118) was merged.
