### ISSUE TITLE
unable to run Angular example

### ISSUE THREAD

**Issue by bpieslak** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#48]
Hi,
  I'm really excited to try and use the GroupDocs viewer, but I am unfortunately running into an issue trying to launch the Angular example

  I've cloned the latest of /master from this repo, running Node 12.12.0 and Angular CLI 8.0.0 with Angular 8.2.11.

  After pulling code, I deleted `node_modules` and ran `yarn install` to re-download all of the packages all node dependencies.  Then I run `ng serve viewer`  (or `npm start`), and it looks like everything compiles correctly and the development server is available at http://localhost:4200/

  However, when I load the application in my browser, I encounter a 404 error when the application requests `http://localhost:4200/viewer/loadConfig`

   Anything I'm doing wrong?

Thanks!
-Brian

![image](https://user-images.githubusercontent.com/16921498/66884423-27517880-ef9f-11e9-8015-7717a3b93bca.png)

![image](https://user-images.githubusercontent.com/16921498/66884429-2c162c80-ef9f-11e9-8573-d8fbca133787.png)

![image](https://user-images.githubusercontent.com/16921498/66884434-30dae080-ef9f-11e9-84ec-7e7d9f6bf2ac.png)

![image](https://user-images.githubusercontent.com/16921498/66884456-3e906600-ef9f-11e9-8dcf-e327831302ab.png)

**Comment by kegor** [comment]
Hi @bpieslak, could you please try to make just `Clean->Rebuild` and then `Run` in your VS on opened `GroupDocs.Viewer MVC` solution?

**Comment by bpieslak** [comment]
Hi @kegor .  thank you for the quick response.  
Apologies for my confusion earlier.  I see how this is working now.

Very cool stuff.
-Brian
