### ISSUE TITLE
Upgrade to v19.8 of GroupDocs.Viewer for .NET

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#50]
Do you have any plans to upgrade to [v19.8](https://docs.groupdocs.com/display/viewernet/GroupDocs.Viewer+for+.NET+19.8+Release+Notes)  (or greater) of GroupDocs.Viewer for .NET API?

**Comment by kegor** [comment]
Hi @usmanazizgroupdocs, yes, we plan to start this upgrade at the next week.

**Comment by kegor** [comment]
@usmanazizgroupdocs, we met some issues during update process, we expect to release upgraded version after GroupDocs.Viewer next release.

**Comment by usmanazizgroupdocs** [comment]
@kegor Thanks.

**Comment by bobkovalex** [comment]
@usman-aziz 

GroupDocs.Viewer for .NET API has been updated to 20.3.
Please checkout latest commit from master branch.

Regards
