### ISSUE TITLE
Excel Gridlines are disabled but appear in Viewer application 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#52]
This issue is raised in https://forum.groupdocs.com/t/excel-gridlines/7930.
Hi, 
If we disable the Gridlines (uncheck gridlines checkbox in view tab in Excel) in a spreadsheet and render it using Viewer. Gridlines start appearing. However, I cannot reproduce this issue using API version 19.12 (in console application). Please find the concerned files attached. 
Can you please see how this could be fixed in this UI project?
Thanks 
[Screenshots.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/files/4055097/Screenshots.zip)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, we were able to reproduce this issue, and now it is under investigation.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs
The issue has been fixed.
Please pull latest commit from master branch.

**Note** option 'showGridLines' has value 'true' by default in the configuration.yml file.
