### ISSUE TITLE
GroupDocs.Viewer for .NET UI in pure JS

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#56]
This issue is raised in https://forum.groupdocs.com/t/net-viewer-toolbar/8040/3

Hi,
Is there any plan for providing a pure/only JavaScript based UI project? 

Thanks

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

> Is there any plan for providing a pure/only JavaScript based UI project?

No, there is not.

But you can checkout following [commit](6f66698c819ae7a3f4d9bfd44dcba71e8c95110b) which uses latest jQuery implementation, before we moved to Angular or you can try following [project](https://github.com/bobkovalex/QuickView-.NET-MVC) which is an early prototype for GroupDocs.Viewer UI and it has built-in resources.

**Please note**: jQuery is discontinued, so in case of any issues, we won't be able to fix them.
