### ISSUE TITLE
Lack of RTL support for PowerPoint document 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#57]
This issue is raised in https://forum.groupdocs.com/t/lack-of-rtl-support-in-powerpoint-files/8041

Hi,
Please find the attached PPTX [test.pptx](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/files/4233128/test.pptx). If we view it in the application, second page doesn't render properly. There seems a lack of RTL support. 
![output](https://user-images.githubusercontent.com/15940608/74981275-cc9bc200-5453-11ea-8017-e0156231cf7b.JPG).

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

Issue has been fixed.
Please checkout latest commit from master.

Regards
