### ISSUE TITLE
Incorrect font heading when PDF file is rendered

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#58]
Hi,

Please find the problematic file and the output screenshot attached.
[sample files.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/files/4326453/sample.files.zip)

Some headings are picking up the incorrect font family.
Thanks

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

This issue will be fixed by resolving issue #50 
We added it to our roadmap.
Thanks.

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

The issue has been fixed.
Please checkout latest commit from master branch.

Regards
