### ISSUE TITLE
Problem with summary when rendering a PDF to HTML 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#61]
This issue is raised in https://forum.groupdocs.com/t/problems-with-summary-link-to-some-part-of-the-document-with-pdf-when-rendering-to-html/8318

Hi,
It's been observed that when we render a Word file with summary and click on a link to navigate to a specific page, it works fine. 
But in case of PDF there's an issue. When using a PDF that has links to some part of the file, the GroupDocs.Viewer doesn’t render the HTML with the anchor to navigate through the file.
Please find the sample files attached. 
Thanks 
[Files used.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/files/4621537/Files.used.zip)

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

We've been able to reproduce the issue.
Currently our PDF engine doesn't support anchors in a document, so we've requested this feature from our product team.
We will work on it and add it as soon as it is ready.

Anyway, I will notify you as soon as it is added.

Regards

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs,
The issue has been fixed, please checkout latest commit from master branch.
