### ISSUE TITLE
Incorrect text and image positioning 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC#62]
This issue is raised in https://forum.groupdocs.com/t/incorrect-position-of-images-and-characters-in-a-docx-file/8328

Hi,

Please find the problematic DOCX file attached - [Sample File.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/files/4631079/Sample.File.zip)
When we open/render this document, some text and images are misplaced. Please have a look at the attached screenshots in order to get clear picture of this issue. 
[Screenshots.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/files/4631094/Screenshots.zip)

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

I've tried to open **sample file** with MS Word and it seems that document has some issues even in native application.

We will continue to investigate this issue, however please ask customer to use well formatted document for test purposes.

See screenshot below on how it looks in MS Word:
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/2103709/82033646-b2b1fa00-96a5-11ea-8bb0-c70a25b18297.png">

Regards
